---
- yum: name={{ item }} state=present
  with_items:
    - bash
    - bzip2
    - coreutils
    - curl
    - gzip
    - man
    - patch
    - sed
    - tar
    - unzip
    - vim
    - wget
    - zip

