---
- template: src=../templates/yum.repo.j2
            dest=/etc/yum.repos.d/vagrant.repo
            owner=root group=root mode=0644
  with_items:
    - { id: vagrant,
        name: 'RPM repository for https://github.com/halvards/vagrant-vm',
        baseurl: 'http://dl.dropbox.com/u/41147122/rpmrepo/common/',
        enabled: 1,
        gpgcheck: 0,
        gpgkey: False }

